//
// Created by aurel on 5/31/23.
//

#pragma once

typedef enum
{
	O_ADD_OP_USERMOD,
	O_RM_OP_USERMOD,
	O_ADD_OP_CHANNELMOD,
	O_RM_OP_CHANNELMOD,
	L_ADD_CLIENTLIMIT_CHANNELMOD,
	L_RM_CLIENTLIMIT_CHANNELMOD,
	I_ADD_INVITEONLY_CHANNELMOD,
	I_RM_INVITEONLY_CHANNELMOD,
	T_ADD_PROTECTEDTOPIC_CHANNELMOD,
	T_RM_PROTECTEDTOPIC_CHANNELMOD,
	K_ADD_KEY_CHANNELMOD,
	K_RM_KEY_CHANNELMOD,
}FLAGS_MODS;

