//
// Created by aurel on 5/31/23.
//

#pragma once

#define I_ADD_INVISIBLE_USERMOD				40
#define I_RM_INVISIBLE_USERMOD				41

#define O_ADD_OP_USERMOD					42
#define O_RM_OP_USERMOD						43

#define R_ADD_REGISITERED_USERMOD			44
#define R_RM_REGISTERED_USERMOD				45

#define B_ADD_BANLIST_CHANNELMOD			46
#define B_RM_BANLIST_CHANNELMOD				47

#define E_ADD_BANEXCEPTIONLIST_CHANNELMOD	48
#define E_RM_BANEXCEPTIONLIST_CHANNELMOD	49

#define L_ADD_CLIENTLIMIT_CHANNELMOD		50
#define L_RM_CLIENTLIMIT_CHANNELMOD			51

#define I_ADD_INVITEONLY_CHANNELMOD			52
#define I_RM_INVITEONLY_CHANNELMOD			53
